### ISSUE TITLE
Connecting to Vagrant from Windows

### ISSUE THREAD

**Issue by aewing** [steelbrain/Atom-Hack#43]
I am trying to connect to a vagrant installation from Windows. I have tried connecting to 127.0.0.1 on port 2222 with the private key generated by vagrant for my machine, but to no avail. Can anyone offer any assistance? I have ssh on my path.

**Comment by steelbrain** [comment]
I've been very busy with other projects lately, didn't test the latest version on windows yet.
I'll investigate and fix in a few hours.

**Comment by aewing** [comment]
Any update on this? I have ssh in my path, and am still getting this error from Atom.

**Comment by steelbrain** [comment]
Sorry, but My schedule is super-tight. I will try to spare some time for it today

**Comment by steelbrain** [comment]
It has been fix, Please upgrade your Atom-Hack.
By the way This is my `.atom-hack` config.
__Note:__ You have to escape backslashes in JSON
__Note:__ You don't need anything in your PATH variable for this to work.
```js
{
  "type":"remote",
  "host":"vm",
  "username":"steel",
  "port":22,
  "privateKey":"D:\\Keys\\id_rsa",
  "remoteDir":"/home/steel/Dev",
  "autoPush":true
}
```
