### ISSUE TITLE
TODO: Create a Package dependency manager for Atom and Consume it

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/Atom-Hack#46]

**Comment by dwlnetnl** [comment]
I'd like also a good dependency/composer/autoload solution. And I'm willing to do coding.

**Comment by steelbrain** [comment]
Thanks, I will start working on it in about a day or twice. Planning to use `https://github.com/atom/service-hub` for it.

**Comment by dwlnetnl** [comment]
I will start working on the Hack library. It would be great if you can take of the Atom part. I've absolutely no experience with developing for Atom.

If I've have a simple skeleton to start with, I will open a GitHub repo.

**Comment by steelbrain** [comment]
Closing, See atom/atom/issues/6013
