### ISSUE TITLE
Fallback to global namespace for functions not supported in autocomplete

### ISSUE THREAD

**Issue by dwlnetnl** [steelbrain/Atom-Hack#51]
When coding inside a namespace, there is a fallback to the global namespace for functions. This is currently not implemented in the autocompletion. (I'm using autocomplete+ by the way.)

**Comment by steelbrain** [comment]
Can you please provide a minimal code snippet to reproduce the bug?

**Comment by dwlnetnl** [comment]
```
<?hh
namespace N;

class C {
  public function f() {
    // here only \str<tab> works
    // not str<tab>
  }
}
```

**Comment by dwlnetnl** [comment]
I've stumbled also on hh_clients autocomplete abilities. Maybe it can be integrated. This would be awesome because hh_client has full knowledge of all the valid symbols.

**Comment by steelbrain** [comment]
I am successfully able to reproduce this behaviour on my machine. and Because Atom-Hack uses `hh_client` from `github.com/facebook/hhvm` for nearly everything and has __zero__ knowledge of namespaces, It can only be implemented by the hhvm folks.

**Comment by steelbrain** [comment]
But maybe you're right, if we recieve an empty list of autocompletions for a scope, Atom-Hack should append `\` in front of it itself and try to get a list.

**Comment by steelbrain** [comment]
Opened in HHVM repo, closing here
