### ISSUE TITLE
wrong name in `activate` requirements

### ISSUE THREAD

**Issue by ashkann** [steelbrain/Atom-Hack#65]
in `Atom-Hack/lib/atom-hack.coffee` 
```
module.exports = LinterHack =
  Hack: null
  activate: ->
    if typeof atom.packages.getLoadedPackage("linter") is 'undefined'
```

cuases the package to emit an error complaining the "linter" package is not found but changing it to
```
    if typeof atom.packages.getLoadedPackage("linter-plus") is 'undefined'
```

resolves the issue (the error goes away).

This makes sense as this package depends on `linter-plus` which has ` name:"linter-plus"` in its `package.json` manifest.

**Comment by ashkann** [comment]
Also,thank you for the excellent work. I wish I could help more but doing two much php has slowed my brain ;-)

**Comment by steelbrain** [comment]
Be advised that `linter-plus` package has been deprecated in favor of `linter` package, the update was pushed yesterday I think

**Comment by ashkann** [comment]
Oh. I see. I believe this not reflected in the documentaion at nuclide.io or perhaps I missed it.

**Comment by steelbrain** [comment]
Yep. also this `atom-hack` is different from the one provided by `nuclide`. It's the one offered by Open Source Community before nuclide was out, I would discuss those guys into taking this name on apm. Also there's an open PR in the nuclide repo that fixes that docs issue.

**Comment by ashkann** [comment]
Thanks for the feedback. This is getting a little confusing :-)
