### ISSUE TITLE
Remote not working on Windows

### ISSUE THREAD

**Issue by dasprot** [steelbrain/Atom-Hack#67]
I have a .hack-config file in my project root on my windows machine and I receive the message "[Hack] Successfully Connected to Server":
```
{
  "type":"remote",
  "host":"redacted.de",
  "username":"redacted",
  "port":4711,
  "privateKey":"D:\\Archiv\\redacted.ppk",
  "remoteDir":"/var/www/redacted",
  "autoPush": true
}
```

HHVM is installed on the remote Linux machine and I'm able to run my script using "hhvm Application.hh" in the same user context as configured in the .hack-config

Though neither atom-hack nor autocomplete-hack is working - no errors, it just happens nothing.

Installed packages: 

Atom-Hack
autocomplete-hack
language-hack
linter
project-manager

**Comment by steelbrain** [comment]
Thanks for the bug report, I'll investigate!

**Comment by dasprot** [comment]
I reinstalled and reconfigured Atom with the same packages. 

Upon saving I receive an Uncaught Error: stream.push() after EOF
I checked my Server and Atom never seems to push the files to the server.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: MATTHIAS-PC
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v5.0.7


### Stack Trace

Uncaught Error: stream.push() after EOF

```
At events.js:141

Error: stream.push() after EOF
  at readableAddChunk (_stream_readable.js:132:15)
  at SFTPStream.Readable.push (_stream_readable.js:109:10)
  at SFTPStream.Transform.push [as __push] (_stream_transform.js:128:32)
  at SFTPStream.push (C:\Users\matthias\.atom\packages\Atom-Hack\node_modules\node-ssh\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:164:18)
  at SFTPStream.open (C:\Users\matthias\.atom\packages\Atom-Hack\node_modules\node-ssh\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:773:15)
  at C:\Users\matthias\.atom\packages\Atom-Hack\node_modules\node-ssh\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:995:11
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:03.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v5.0.7
autocomplete-hack, v1.0.1
language-hack, v0.1.1
linter, v1.2.4
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
I have an SFTP refactor planned, It'll be affecting SFTP speed greatly and will make it super-efficient, stay tuned.

**Comment by steelbrain** [comment]
Just pushed an update people, can you please try that and see if it works for you?

**Comment by dasprot** [comment]
Connection seems fine, I can see my files being updated on the remote machine as I save them locally.

But still there is no error detection/highlighting and no auto completion

**Comment by steelbrain** [comment]
What version are you on? 'cause I tried to reproduce this before and was able to do so with `autoPush` set to off, but it's no longer the case with the latest release.

**Comment by dasprot** [comment]
OS ist Windows 10 (build 10240 / RTM)
Atom 1.0.2
Atom-Hack 5.0.8
autocomplete-hack 1.0.1
linter 1.2.4

You can see an example file here: http://i.imgur.com/DVSdsSn.png

**Comment by steelbrain** [comment]
Ah right! What if I told you that Hack/HHVM doesn't support type checking and/or linting on top level, move your `$T = new Test()` code to a new function called `main` and retry.
Also note that to get the most out of HHVM/Hack You should use it's strict mode, by starting your file with `<?hh //strict`

**Comment by dasprot** [comment]
Thanks for the help, but it should work with this constellation right?

test.hh:
```
<?hh //strict

class Test {

  public function __construct() : void {
  }

  public function doSomething() : void {
    echo 'Done!';
  }

}
```

main.hh
```
<?hh //strict

require_once 'test.hh';

function main() {
  $T = new Test();
  $T->doSomething();
}

main();
```

Or as an alternative main.hh
```
<?hh //strict

require_once 'test.hh';

class Main {
  public function main() {
    $T = new Test();
    $T->doSomething();
  }
}

$Main = new Main();
$Main->main();
```

But still even within my main function there is no autocomplete and no error highlighting.

**Comment by steelbrain** [comment]
HHVM disallows any kind-of top level code except for require, for both autocomplete and type checking. To work around this behavior, facebook folks and myself, we're using some runner files in php, and calling the hack initialization functions from it.
Like
```hack
<?hh //strict
// Main.hh
class Main{
  public static function Init():void{
    Mirror::$DB = new DatabaseConnection()
    Mirror::$Redis = new RedisConnection()
  }
}
```
```hack
<?hh //strict
// Page.hh
class Page{
  public static function Render(): XHPRoot{
    return
      <x:doctype>
        <html>
          <head>
            <title>Hey There</title>
          </head>
          <body>
            Something that belongs to the body
          </body>
        </html>
      </x:doctype>
  }
}
```
```hack
<?php
// Runner.php
require(__DIR__.'/Main.hh');
require(__DIR__.'/Page.hh');
Main::Init();
echo Page::render();
```
now the typechecker will give errors in both the `Main.hh` and `Page.hh` about __EVERYTHING__ since we are in strict mode there and will just ignore `Runner.php`.

**Comment by dasprot** [comment]
Thank you for all the help, I appreciate it!
I modified my Project accordingly - in my Linux machine the typechecker works perfectly (atom-hack configured for local, not remote).

Nothing on my Windows machine though.

**Comment by steelbrain** [comment]
Can you try removing and restarting atom and then installing it again?
