### ISSUE TITLE
Add support for Windows native hh_client

### ISSUE THREAD

**Issue by raeesiqbal** [steelbrain/Atom-Hack#69]
* Remove the error about .`atom-hack` not found when there is a local `hh_client` available.
* Try to restart `hh_client` automatically when it crashes

**Comment by steelbrain** [comment]
We can not detect about `hh_client` without executing it (or without doing some dirty checks).
We can not restart `hh_client` when it crashes as we don't know when it crashes, furthermore it's `hh_server` that crashes not `hh_client` and killing an HH server could lead to a website not working (as it'll have to restart the hh_client) as well as some other unwanted beahvior.
