### ISSUE TITLE
Feature Request: Find definition

### ISSUE THREAD

**Issue by SiebelsTim** [steelbrain/Atom-Hack#70]
Consider this piece of code

```
class LoginController extends WebController {
  ...
}
```

Often, I want to look into the parent class (`WebController`) to look for some methods are somethings similar. It would be so much faster to be able to position your cursor on the parent class and open up the file the class is defined in. Ideally this would also work on typehints that are defined somewhere else.

`hh_client` provides the option `--search-class` for this purpose. I think it is more tricky to find the definition of a method though. (e.g. a call to `parent::__construct()`).

Initially I thought about adding this myself, but I saw this is coffeescript and I have no idea about that, and I know that this probably is non-trivial to implement :P

**Comment by steelbrain** [comment]
I had implemented it in the past but then removed it, Guess I'll be implementing it again

**Comment by steelbrain** [comment]
Fixed by #72
