### ISSUE TITLE
Remote error checking not working

### ISSUE THREAD

**Issue by jdeveth** [steelbrain/Atom-Hack#73]
After updating to Atom-Hack v6.1.0, error checking no longer works. It worked fine before updating (with v5.0.9), so I'm guessing something broke in the new version.

I am developing using vagrant. On the terminal I can get the errors to show up, but only after restarting the hh_client first. It looks like it isn't detecting the files as being changed.

**.atom-hack file**
```
{
  "type":"remote",
  "host":"127.0.0.1",
  "username":"vagrant",
  "port":2222,
  "privateKey":"/home/jeff/bin/hackservice/.vagrant/machines/default/virtualbox/private_key",
  "remoteDir":"/vagrant",
  "autoPush": false
}
```

**Installed packages**
```
Atom-Hack v6.1.0
autocomplete-hack v2.0.0
dockblockr v0.7.3
language-hack v0.1.1
linter v1.6.0
```

**Comment by steelbrain** [comment]
Interesting. How about you run save the file, it doesn't notice the changes, then you touch that file from the terminal, then save that file again and see if it detects changes.

**Comment by jdeveth** [comment]
Touching the file from the terminal doesn't change anything inside of Atom, still no errors. When checking on the terminal though, it does show the current errors correctly after touching it.

Saving the file does change the last modified date of the file however.

**Comment by steelbrain** [comment]
how about a `touch -am $FILE`?

**Comment by jdeveth** [comment]
That was what I did before, sorry if that wasn't clear.

**Comment by steelbrain** [comment]
Can we have this talk on atom slack? atom-slack.herokuapp.com

**Comment by jdeveth** [comment]
When checking again on the same machine today, everything works without a problem. Errors are being shown in Atom as intended. 
I didn't change anything, so I'm not sure what caused it not to work yesterday while it does work today.

**Comment by steelbrain** [comment]
Closing for now, feel free to tell me if you experience this again.
