### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by HakuDouga** [steelbrain/Atom-Hack#74]
**.hack-atom:**
`{
"type":"remote",
"host":"something-dev",
"username":"root",
"port":22,
"privateKey":"C:/.ssh/id_rsa",
"remoteDir":"/usr/share/nginx/something",
"autoPush":false
}`

base.js:107: console.log(options.cwd)

**Console log:**
>D:\Projects\Something
>D:\Projects\Something
>/usr/share/nginx/Something 
>/usr\share\nginx\Something
>\

**Comment by steelbrain** [comment]
Thanks for the bug report.

**Comment by steelbrain** [comment]
We could use https://atom.io/docs/api/v1.0.19/Project#instance-relativizePath instead of having a `localPath` field in the package manifest, it'll make things very simpler.

**Comment by steelbrain** [comment]
Fixed by #76 and #75
